repos:
  - repo: local
    hooks:
      - id: pylint
        name: Run Pylint on backend/app/
        entry: bash -c "PYTHONPATH=$PWD/backend pylint backend/app/"
        language: system
        types: [python]
        args: ['--fail-under=8']
